const rarityConfig = {
    'bg_Black Check': 1,
    'bg_Blue Check': 1,
    'bg_Blue': 1,
    'bg_Brown': 1,
    'bg_Bubble': 2,
    'bg_Coral': 1,
    'bg_Fog': 1,
    'bg_Gray': 1,
    'bg_Green Gradient': 1,
    'bg_Light Blue': 1,
    'bg_Light Green': 1,
    'bg_Miami': 2,
    'bg_Newyork': 2,
    'bg_Orange Gradient': 1,
    'bg_Orange Pattern': 2,
    'bg_Orange': 1,
    'bg_Pink Gradient': 1,
    'bg_Pink': 1,
    'bg_Purple Pattern': 2,
    'bg_Purple': 1,
    'bg_Rainbow Gradient': 1,
    'bg_Rainbow': 2,
    'bg_Sky': 2,
    'bg_Twinkle': 2,
    'bg_Universe Gradient': 1,
    'bg_Yellow': 1,
    'skin_Blue': 1,
    'skin_Brown': 1,
    'skin_Gray': 1,
    'skin_Light Blue': 1,
    'skin_Light Brown': 1,
    'skin_Light Yellow': 1,
    'skin_Pink': 1,
    'skin_Purple': 1,
    'body_Angel Wings': 3,
    'body_Basketball Uniform': 2,
    'body_Bathrobe': 3,
    'body_Black Jacket': 1,
    'body_Blue Bell': 1,
    'body_Blue Checkered Shirt': 2,
    'body_Blue Hoodie': 1,
    'body_Blue Jacket': 1,
    'body_Brown Checkered Shirt': 2,
    'body_Butterfly Wings': 3,
    'body_Carrot Hoodie': 1,
    'body_Cat Hoodie': 3,
    'body_Classic Shirt': 3,
    'body_Dark Green Scarf': 1,
    'body_Devil Wings': 3,
    'body_Gray Shirt': 2,
    'body_Green Hoodie': 1,
    'body_Green Scarf': 1,
    'body_Green Shirt': 2,
    'body_Heart Crop Top': 1,
    'body_Heart Hoodie': 1,
    'body_Mummy': 3,
    'body_Overalls': 3,
    'body_Pastel Knitwear': 2,
    'body_Pink Shirt': 2,
    'body_Polka Dot Cape': 1,
    'body_Purple Checkered Shirt': 2,
    'body_Purple Hoodie': 1,
    'body_Rainbow Cape': 3,
    'body_Rainbow Hoodie': 1,
    'body_Rainbow Shirt': 2,
    'body_Red Bell': 1,
    'body_Red Cape': 1,
    'body_Red Scarf': 1,
    'body_Rider Cape': 2,
    'body_Santa': 3,
    'body_Skyblue Knitwear': 1,
    'body_Sleeveless Shirt': 1,
    'body_Smile Hoodie': 1,
    'body_Star Hoodie': 1,
    'body_Striped Hoodie': 1,
    'body_Summer Sleeveless Shirt': 2,
    'body_Tattoo': 3,
    'body_Yellow Jacket': 1,
    'face_3D Glasses': 3,
    'face_American Face': 3,
    'face_Angry': 2,
    'face_Beam': 1,
    'face_Blindfold': 2,
    'face_Bomb': 3,
    'face_Box': 3,
    'face_Bubble': 1,
    'face_Candy': 1,
    'face_Cheeky': 1,
    'face_Crack': 1,
    'face_Dark Circles': 1,
    'face_Dizzy': 1,
    'face_Dotted Face': 1,
    'face_Eyepatch': 2,
    'face_Fight': 2,
    'face_Freckle': 1,
    'face_Fried Egg': 1,
    'face_Goggles': 2,
    'face_Hole': 3,
    'face_Leon': 2,
    'face_Love': 1,
    'face_Mask': 2,
    'face_Masquerade': 2,
    'face_Metaverse': 3,
    'face_Mole': 1,
    'face_Piercing': 1,
    'face_Pipe': 2,
    'face_Radom': 1,
    'face_Rainbow Puke': 3,
    'face_Rich': 2,
    'face_Rose Mask': 2,
    'face_Rudolph': 1,
    'face_Shameful': 1,
    'face_Smile': 1,
    'face_Smiling Paper': 2,
    'face_Spring Eyeball Glasses': 2,
    'face_Strange Glasses': 2,
    'face_Sunflower': 1,
    'face_Sunglasses': 3,
    'face_Tease Ya': 1,
    'face_Terminator': 3,
    'face_White Beard': 1,
    'face_Zipper': 2,
    'face_Zombie': 2,
    'hair_Amulet': 1,
    'hair_Angel Ring': 3,
    'hair_Arrow': 1,
    'hair_Bandana': 2,
    'hair_Beer': 1,
    'hair_Bluetooth Earphone': 1,
    'hair_Bump': 1,
    'hair_Candles': 1,
    'hair_Chef Hat': 1,
    'hair_Chick': 3,
    'hair_Cupcake': 1,
    'hair_Flower Hairband': 2,
    'hair_Frappuccino': 1,
    'hair_Fried Egg': 1,
    'hair_Glove': 3,
    'hair_Green Cap': 2,
    'hair_Green Sun Cap': 2,
    'hair_Hair Roll': 1,
    'hair_Hamburger': 1,
    'hair_Hands': 1,
    'hair_Headset': 3,
    'hair_Heart Arrow': 1,
    'hair_Heart Winter Hat': 2,
    'hair_Highlighter Perm': 3,
    'hair_Ice Cream': 1,
    'hair_Leaf': 1,
    'hair_Magician Hat': 1,
    'hair_Mask': 3,
    'hair_Money': 1,
    'hair_Mushroom': 1,
    'hair_Pearl Earrings': 1,
    'hair_Pencil': 1,
    'hair_Perm': 2,
    'hair_Pill': 1,
    'hair_Pink Ribbon': 2,
    'hair_Pizza': 1,
    'hair_Popcorn': 1,
    'hair_Random Box': 1,
    'hair_Red Beanie': 3,
    'hair_Red Comb': 1,
    'hair_Reggae Hair': 3,
    'hair_Rice Cake Skewer': 1,
    'hair_Screw': 1,
    'hair_Sleeping Hat': 1,
    'hair_Sock': 1,
    'hair_Sprout': 1,
    'hair_Triple Earrings': 1,
    'hair_Umbrella': 1,
    'hair_Winter Hat': 2
}

function getRarity(traitType, traitValue) {
    const rarityConfigKey = traitType + '_' + traitValue;
    return Number(rarityConfig[rarityConfigKey]);
}

module.exports = {rarityConfig, getRarity};